### ISSUE TITLE
rename and refactor pipes

### ISSUE THREAD

**Issue by ktawaststjerna** [ktawaststjerna/gift-list#40]
# Description
https://github.com/ktawaststjerna/gift-list/blob/master/app/models/pipe.rb

Pipe is a polymorphic, many to many table that's used for... 
1) Connecting many Users to many Families
2) Connecting many Families to many Items

# Todo
- [x] We need to rename 1) to UsersToFamilies and make it a single use table
- [x] We need to rename 2) to FamiliesToItems and make it a single use table
- [x] Look into PipeConcern and see if it's useful
